on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@master
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create ACR
      id: create-acr
      run: |
        az acr create -n azwest2repo -g azwest2repo8dae-rg --location "West US 2" --sku Standard --admin-enabled
        echo "::set-output name=acr_username::`az acr credential show -n azwest2repo --query username | xargs`"
        echo "::set-output name=acr_password::`az acr credential show -n azwest2repo --query passwords[0].value | xargs`"
        echo "::add-mask::`az acr credential show -n azwest2repo --query passwords[0].value | xargs`"

    - uses: azure/docker-login@v1
      with:
        login-server: azwest2repo.azurecr.io
        username: ${{ steps.create-acr.outputs.acr_username }}
        password: ${{ steps.create-acr.outputs.acr_password }}

    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/python-docker" -f  "python-docker/Dockerfile" -t azwest2repo.azurecr.io/ultimateboaraks:${{ github.sha }} --label dockerfile-path=python-docker/Dockerfile
        docker push azwest2repo.azurecr.io/ultimateboaraks:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      id: login
      with:
         kubeconfig: ${{ secrets.aks_ultimateboaraks_kubeConfig }}
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep python-docker-ns | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace python-docker-ns`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: python-docker-ns
        container-registry-url: azwest2repo.azurecr.io
        container-registry-username: ${{ steps.create-acr.outputs.acr_username }}
        container-registry-password: ${{ steps.create-acr.outputs.acr_password }}
        secret-name: ultimateboardockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: python-docker-ns
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          azwest2repo.azurecr.io/ultimateboaraks:${{ github.sha }}
        imagepullsecrets: |
          ultimateboardockerauth   
